#include "variant.h"

/*
 * Pins descriptions
 */
const PinDescription pins_description_map[]=
{

  { GPIOB,  GPIO_Pin_11, (PIN_ATTR_NONE), ADC_NONE}, //  D0 / B11 / UART0 RX
  { GPIOB,  GPIO_Pin_10, (PIN_ATTR_NONE), ADC_NONE}, //  D1 / B10 / UART0 TX
  { GPIOB,  GPIO_Pin_9, (PIN_ATTR_NONE), ADC_NONE}, //   D2 / B9 / UART1 RX
  { GPIOA,  GPIO_Pin_13, (PIN_ATTR_PWM), ADC_NONE}, //   D3 / A13 / PWM_2_B
  { GPIOA,  GPIO_Pin_14, (PIN_ATTR_TIMER_IN), ADC_NONE}, //   D4 / A14 / TMR_0_IN
  { GPIOA,  GPIO_Pin_15, (PIN_ATTR_TIMER_IN), ADC_NONE}, //   D5 / A15 / TMR_1_IN
  { GPIOA,  GPIO_Pin_11, (PIN_ATTR_PWM), ADC_NONE}, //   D6 / A11 / PWM_1_B
  { GPIOB,  GPIO_Pin_8, (PIN_ATTR_NONE), ADC_NONE}, //   D7 / B8 / UART1 TX
  { GPIOA,  GPIO_Pin_4, (PIN_ATTR_NONE), ADC_NONE}, //   D8 / A4 / ECAP0_IO
  { GPIOA,  GPIO_Pin_10, (PIN_ATTR_PWM), ADC_NONE}, //   D9 / A10 / PWM_1_A
  { GPIOB,  GPIO_Pin_4, (PIN_ATTR_NONE), ADC_NONE}, //   D10 / B4 / SPI_CS
  { GPIOB,  GPIO_Pin_7, (PIN_ATTR_NONE), ADC_NONE}, //   D11 / B7 / SPI_MOSI
  { GPIOB,  GPIO_Pin_6, (PIN_ATTR_NONE), ADC_NONE}, //   D12 / B6 / SPI_MISO
  { GPIOB,  GPIO_Pin_5, (PIN_ATTR_NONE), ADC_NONE}, //   D13 / B5 / SPI_SCK

  { GPIOB,  GPIO_Pin_0, (PIN_ATTR_ANALOG | PIN_ATTR_NEED_LS_CTRL), ADC_CH_NUM(0)}, //   A0 / B0 / ADC_0
  { GPIOB,  GPIO_Pin_1, (PIN_ATTR_ANALOG | PIN_ATTR_NEED_LS_CTRL), ADC_CH_NUM(1)}, //   A1 / B1 / ADC_1
  { GPIOB,  GPIO_Pin_2, (PIN_ATTR_ANALOG | PIN_ATTR_NEED_LS_CTRL), ADC_CH_NUM(2)}, //   A2 / B2 / ADC_2
  { GPIOB,  GPIO_Pin_3, (PIN_ATTR_ANALOG | PIN_ATTR_NEED_LS_CTRL), ADC_CH_NUM(3)}, //   A3 / B3 / ADC_3

  { GPIOA,  GPIO_Pin_0, (PIN_ATTR_NONE), ADC_NONE}, //   A4 / A0 / I2C_SCL
  { GPIOA,  GPIO_Pin_1, (PIN_ATTR_NONE), ADC_NONE}, //   A5 / A1 / I2C_SDA

  { GPIOA,  GPIO_Pin_6, (PIN_ATTR_NONE), ADC_NONE}, //   USER_BTN / A6 / USER_BTN

  { GPIOB,  GPIO_Pin_12, (PIN_ATTR_LVL_SHIFTER_CTRL), ADC_NONE}, //   LS_0 / B12 
  { GPIOB,  GPIO_Pin_13, (PIN_ATTR_LVL_SHIFTER_CTRL), ADC_NONE}, //   LS_1 / B13 
  { GPIOB,  GPIO_Pin_14, (PIN_ATTR_LVL_SHIFTER_CTRL), ADC_NONE}, //   LS_2 / B14 
  { GPIOB,  GPIO_Pin_15, (PIN_ATTR_LVL_SHIFTER_CTRL), ADC_NONE}, //   LS_3 / B15 


} ;

const pin_size_t adc_ls_ctrl_map[] = 
{
    PIN_LS_0,
    PIN_LS_1,
    PIN_LS_2,
    PIN_LS_3
};

